# Generated by Django 3.2.4 on 2021-06-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name="algorithm's name")),
                ('can_continuous_actions', models.BooleanField(verbose_name='Compatible with continuous actions')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name given to the parameter')),
                ('t', models.IntegerField(choices=[(1, 'Bool'), (2, 'Int'), (3, 'Float'), (4, 'Str')], verbose_name='Type of the parameter')),
                ('def_value_bool', models.BooleanField()),
                ('def_value_int', models.IntegerField()),
                ('def_value_float', models.FloatField()),
                ('def_value_str', models.CharField(max_length=64)),
                ('algo', models.ManyToManyField(to='shepherd.Algorithm', verbose_name='Algorithms that has this parameter')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name="user's username")),
                ('email_address', models.EmailField(max_length=64, verbose_name="user's email address")),
            ],
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_bool', models.BooleanField()),
                ('value_int', models.IntegerField()),
                ('value_float', models.FloatField()),
                ('value_str', models.CharField(max_length=64)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shepherd.agent', verbose_name='Agent for which this parameter has a value')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shepherd.parameter', verbose_name='Parameter set to the value')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='algo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shepherd.algorithm', verbose_name='RL algorithm executed by this agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shepherd.user', verbose_name='user that owns this agent'),
        ),
    ]
