# Generated by Django 3.2.4 on 2021-06-09 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shepherd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user that owns this agent'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
