# Generated by Django 3.2.4 on 2021-06-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0002_auto_20210609_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametervalue',
            name='value_bool',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='value_float',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='value_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='value_str',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
