# Generated by Django 3.2.4 on 2021-06-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0003_auto_20210609_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='def_value_bool',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='def_value_float',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='def_value_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='def_value_str',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
