# Generated by Django 3.2.4 on 2021-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0004_auto_20210609_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='action_space',
            field=models.TextField(default='', verbose_name='Action space JSON'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='observation_space',
            field=models.TextField(default='', verbose_name='Observation space JSON'),
            preserve_default=False,
        ),
    ]
