# Generated by Django 3.2.4 on 2021-06-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0005_auto_20210609_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='def_value_bool',
            new_name='value_bool',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='def_value_float',
            new_name='value_float',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='def_value_int',
            new_name='value_int',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='def_value_str',
            new_name='value_str',
        ),
    ]
