# Generated by Django 3.2.5 on 2021-07-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0007_auto_20210614_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='policy',
            field=models.CharField(choices=[('MlpPolicy', 'MlpPolicy: states that are lists of floats'), ('CnnPolicy', 'CnnPolicy: states that are images or 2D arrays')], default='MlpPolicy', max_length=32, verbose_name='Policy class'),
            preserve_default=False,
        ),
    ]
