# Generated by Django 3.2.5 on 2021-08-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0008_agent_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date-time of the episode')),
                ('ret', models.FloatField(verbose_name='Return obtained during that episode')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shepherd.agent', verbose_name='Agent')),
            ],
        ),
    ]
