# Generated by Django 3.2.5 on 2022-01-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0011_auto_20220119_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='policy',
        ),
        migrations.AlterField(
            model_name='agent',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation of the agent'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='5d97d8d5-7807-4440-bfc6-14c3586e45e8', max_length=36, unique=True, verbose_name='API Key string'),
        ),
    ]
