# Generated by Django 3.2.5 on 2022-01-20 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0012_auto_20220120_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_activity_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of last usage of the agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='max_percent_cpu_usage',
            field=models.FloatField(default=100.0, verbose_name='Maximum CPU usage in percentage points (100.0 = 1 full CPU used every one-minute interval)'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='3bb75197-bc80-439f-8cb2-9e4c94027b32', max_length=36, unique=True, verbose_name='API Key string'),
        ),
    ]
