# Generated by Django 3.2.5 on 2022-01-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0013_auto_20220120_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='value_str',
            new_name='default_value',
        ),
        migrations.RenameField(
            model_name='parametervalue',
            old_name='value_str',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='value_bool',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='value_float',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='value_int',
        ),
        migrations.RemoveField(
            model_name='parametervalue',
            name='value_bool',
        ),
        migrations.RemoveField(
            model_name='parametervalue',
            name='value_float',
        ),
        migrations.RemoveField(
            model_name='parametervalue',
            name='value_int',
        ),
        migrations.AddField(
            model_name='agent',
            name='parameters',
            field=models.ManyToManyField(help_text='Parameters used to configure the learning algorithm used by the agent', through='shepherd.ParameterValue', to='shepherd.Parameter'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='798b9b35-f28d-4c2d-85e8-73006b54a056', max_length=36, unique=True, verbose_name='API Key string'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='algo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shepherd.algorithm', verbose_name='Algorithm that has this parameter'),
        ),
    ]
