# Generated by Django 4.0.2 on 2022-02-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0014_auto_20220121_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='name',
            field=models.CharField(default='Unnamed agent', max_length=128, verbose_name='Descriptive name given to the agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='action_space',
            field=models.TextField(help_text='Syntax: either an integer like "4", indicating a discrete number of actions (integers from 0 to 3); a list of 3 elements (shape, low, high) like "[[28], 0.0, 1.0]" indicating a continuous action made of a list of 28 floating-point numbers between 0 and 1; or a dictionary (see Observation Space JSON, as it is only used for observations)', verbose_name='Action space JSON'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='max_percent_cpu_usage',
            field=models.FloatField(default=100.0, help_text='100.0 = 1 full CPU used every one-minute interval', verbose_name='Maximum CPU usage in percentage points'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='observation_space',
            field=models.TextField(help_text='Same syntax as Action Space JSON. It is also possible to have a dictionary of keys to integers or lists (as described above), for environments that produce readings from multiple sensors, such as 16 distance sensors and an 80x80 color camera: {"distance": [[16], 0.0, 1.0], "camera": [[80, 80, 3], 0, 255]}.', verbose_name='Observation space JSON'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='22dd2f4b-8d1f-4a9b-ad95-f48b7de0d23b', max_length=36, unique=True, verbose_name='API Key string'),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shepherd.parameter', verbose_name='Parameter'),
        ),
    ]
