# Generated by Django 4.0.2 on 2022-02-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepherd', '0015_agent_name_alter_agent_action_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='enable_learning',
            field=models.BooleanField(default=True, help_text='True for normal behavior. If False, the agent performs its task (it selects actions) but ignores the rewards it gets and does not update its policy. Useful in production of stable behavior is required.', verbose_name='Enable learning'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='be16ad4f-803a-4d0c-a0c7-6a222bb137db', max_length=36, unique=True, verbose_name='API Key string'),
        ),
    ]
